version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    rebase-strategy: auto
    ignore:
      - dependency-name: eslint
        versions: ['>=10.0.0']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
