export type ScannerExtractor = 'regex-tag' | 'maestro-tags';

export interface PlatformScannerConfig {
    name: string;
    dir: string;
    extractor: ScannerExtractor;
    ignore?: string[];
    linkPrefix?: string;
}

export interface MarkdownRenderConfig {
    banner?: string[];
    title?: string;
    intro?: string[];
    goals?: string[];
    legendRows?: [string, string][];
    footerHints?: string[];
}

export interface TestproofConfig {
    ledger: string;
    platforms: PlatformScannerConfig[];
    coreAreaIds?: string[];
    output?: {
        markdown?: string;
        html?: string;
    };
    markdown?: MarkdownRenderConfig;
    server?: {
        url?: string;
        token?: string;
        projectId?: string;
    };
}

export function defineConfig(config: TestproofConfig): TestproofConfig {
    return config;
}

export const DEFAULT_MARKDOWN: Required<Pick<MarkdownRenderConfig, 'title'>> & MarkdownRenderConfig = {
    title: 'Test Flows & Coverage',
    banner: [
        '<!-- Generated by `testproof generate`. Do not edit by hand. -->',
        '<!-- Source of truth: the ledger YAML — coverage derived from scanner tags -->',
    ],
    intro: [
        'Source of truth for **what must work**, plus honest automation coverage.',
        '**Definitions** live in the ledger YAML; this file is **generated**.',
    ],
    goals: [
        'Create automated tests for the flows below that cover:',
        '',
        '- Functionality',
        '- Accessibility',
    ],
    legendRows: [
        ['`FLOW-…`', 'Stable hierarchical ID for this branch'],
        ['`[x]`', 'Fully automated for that **exact** branch (spec/flow linked)'],
        ['`[ ]`', 'Not fully automated — still required'],
        ['`todo`', 'Needs automation'],
        ['`Partial`', 'Thin coverage exists; not full for that platform'],
        ['`manual` / `done`', 'Verified by hand (or fixed); not owned by E2E yet'],
    ],
};

export function isCoreAreaId(areaId: string, coreAreaIds?: string[]): boolean {
    return (coreAreaIds ?? []).includes(areaId);
}
